id: P000291
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 2021-12-16 15:32:19.568556
source_metadata:
  id: bdr:W3CN8043
  title: ཁྲོམ་དགེ་སྒྲུབ་སྒྲོན་མའི་དག་སྣང་སོགས།
  author: ''
  volumes:
    149558b2bcdc4f5ab3b49a7e235b7d9c:
      image_group_id: I3CN8045
      title: Volume 1 of khrom dge sgrub sgron ma'i dag snang sogs/
      volume_number: 1
      total_pages: 392
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
